// Content for the forest+trees engine: how one commit gets through Gateforge.
// Facts checked against /home/ukd/Work/gateforge (pre-commit.ts, trusted-policy.ts,
// witness/README.md, core/receipt, cli README, init.ts POLICIES_TEMPLATE, next.ts).
const ECO = {
  title: 'How one commit gets through Gateforge',
  recapView: { x: -200, y: 30, w: 2000, h: 1000 },
  recapTop: 680,
  recapLeft: 40,
  forestView: { x: 30, y: 70, w: 1550, h: 640 },
  forest: {
    boxW: 260, boxH: 130,
    order: ['agent', 'freeze', 'owner', 'start', 'read', 'run', 'grade', 'gate'],
    boxes: [
      { id: 'agent', n: 1, name: 'The agent', short: 'Agent', x: 100, y: 120, pict: [['robot', 97, 10, 0.5]] },
      { id: 'freeze', n: 2, name: 'Freeze', short: 'Freeze', x: 480, y: 120, pict: [['camera', 72, 18, 0.48], ['lock', 166, 30, 0.62]] },
      { id: 'owner', n: 3, name: "Owner's OK", short: "Owner's OK", x: 860, y: 120, pict: [['person', 70, 12, 0.52], ['key', 142, 44, 0.55]] },
      { id: 'start', n: 4, name: 'Start the app', short: 'Start app', x: 1240, y: 120, pict: [['server', 64, 14, 0.44], ['dbIcon', 150, 15, 0.52]] },
      { id: 'read', n: 5, name: 'Read the code', short: 'Read code', x: 100, y: 470, pict: [['doc', 80, 12, 0.62], ['magnifier', 122, 26, 0.48]] },
      { id: 'run', n: 6, name: 'Test run', short: 'Test run', x: 480, y: 470, lanes: ['test runner', 'referee', 'app + database'] },
      { id: 'grade', n: 7, name: 'Grade', short: 'Grade', x: 860, y: 470, pict: [['checklistIcon', 96, 12, 0.62]] },
      { id: 'gate', n: 8, name: 'The gate', short: 'Gate', x: 1240, y: 470, pict: [['gateIcon', 77, 20, 0.56]] },
    ],
    links: [
      { from: 'agent', to: 'freeze', label: 'staged\nfiles', pts: [[360, 185], [476, 185]] },
      { from: 'freeze', to: 'owner', label: 'snapshot', pts: [[740, 185], [856, 185]] },
      { from: 'owner', to: 'start', label: 'approved\nrecipe', pts: [[1120, 185], [1236, 185]] },
      { from: 'start', to: 'read', label: 'snapshot', labelAt: [800, 333], pts: [[1370, 250], [1370, 345], [230, 345], [230, 466]] },
      { from: 'start', to: 'run', label: 'app running', dashed: true, labelAt: [1080, 398], pts: [[1500, 185], [1552, 185], [1552, 410], [610, 410], [610, 444]] },
      { from: 'read', to: 'run', label: 'must-prove\nlist', pts: [[360, 535], [476, 535]] },
      { from: 'run', to: 'grade', label: 'sealed\nreceipt', pts: [[740, 535], [856, 535]] },
      { from: 'grade', to: 'gate', label: 'verdicts', pts: [[1120, 535], [1236, 535]] },
    ],
    bracket: { x: 462, y: 452, w: 296, h: 166, label: 'runs in parallel' },
  },

  scenes: {
    agent: {
      ports: { out: { art: 'staged\nfiles', to: 'Freeze' } },
      actors: [
        { id: 'robot', type: 'robot', x: 230, y: 280, label: 'the agent' },
        { id: 'code', type: 'file', x: 420, y: 60, w: 720, name: 'app/routes/orders.py', who: 'by the agent · example app', typed: true,
          lines: ['@router.delete("/api/orders/{order_id}")', 'def delete_order(order_id: int):', '    db.delete(Order, order_id)', '    return Response(status_code=204)'] },
        { id: 'term', type: 'terminal', x: 420, y: 316, w: 720, rows: 1 },
        { id: 'hook', type: 'hook', x: 1200, y: 250, label: 'Git pre-commit\nhook' },
        { id: 'help', type: 'file', x: 420, y: 450, w: 720, name: 'gateforge --help', who: 'real help text',
          lines: ['pre-commit --scope staged|full', '  freeze the Git index, run the witnessed gate…'] },
      ],
    },
    freeze: {
      ports: { in: [{ art: 'staged\nfiles', from: 'The agent' }], out: { art: 'snapshot', to: "Owner's OK" } },
      actors: [
        { id: 'staged', type: 'folder', x: 300, y: 250, label: 'staged files\n(the Git index)' },
        { id: 'cam', type: 'camera', x: 620, y: 50 },
        { id: 'snap', type: 'file', x: 610, y: 290, w: 340, name: 'Frozen version', lines: ['Git tree ID: 9c2e…', 'Not another folder'] },
        { id: 'scratch', type: 'folder', x: 1050, y: 290, label: 'scratch checkout\n(files to run)' },
        { id: 'robot', type: 'robot', x: 285, y: 545, label: 'the agent' },
      ],
    },
    owner: {
      ports: { in: [{ art: 'snapshot', from: 'Freeze' }], out: { art: 'approved\nrecipe', to: 'Start the app' } },
      actors: [
        { id: 'rules', type: 'file', x: 230, y: 50, w: 620, name: 'rules inside the snapshot', who: 'fingerprinted',
          lines: ['.gateforge.yml', '.gateforge/policies.yml', '.gateforge/classification-policy.yml', '.gateforge/test-map.yml', '.gateforge/runtime.yml'] },
        { id: 'fp', type: 'chip', x: 360, y: 375, w: 360, text: 'fingerprint  a3f9…' },
        { id: 'owner', type: 'person', x: 1130, y: 60, label: 'the owner' },
        { id: 'pin', type: 'key', x: 900, y: 370, label: "owner's pin, outside repo", fp: 'a3f9…' },
        { id: 'robot', type: 'robot', x: 1120, y: 480, label: 'the agent' },
        { id: 'block', type: 'chip', x: 230, y: 470, color: '#dc2626', text: 'have the owner approve and repin the revision, then rerun' },
      ],
    },
    start: {
      ports: { in: [{ art: 'approved\nrecipe', from: "Owner's OK" }], out: { art: 'app\nrunning', to: 'Test run' } },
      actors: [
        { id: 'recipe', type: 'file', x: 220, y: 40, w: 620, name: '.gateforge/runtime.yml', who: 'owner reviews · shortened',
          lines: ['prepare:', "  commands: [['./scripts/install.sh']]", 'services_up:', "  commands: [['./scripts/start-stack.sh']]", 'healthcheck:', "  commands: [['./scripts/health.sh']]"] },
        { id: 'bar', type: 'bar', x: 220, y: 362, w: 620, label: 'prepare: installing' },
        { id: 'snap', type: 'folder', x: 320, y: 470, label: 'scratch checkout' },
        { id: 'server', type: 'server', x: 990, y: 50, label: 'app server' },
        { id: 'db', type: 'db', x: 950, y: 330, label: 'database', rows: [['41', 'cup'], ['42', 'pen'], ['43', 'ink']] },
      ],
    },
    read: {
      ports: { in: [{ art: 'snapshot', from: 'Freeze' }], out: { art: 'must-prove\nlist', to: 'Test run' } },
      actors: [
        { id: 'front', type: 'file', x: 220, y: 40, w: 660, name: 'web/src/orders.js', who: 'example app', lines: ["fetch(`/api/orders/${id}`, {method: 'DELETE'})"] },
        { id: 'routes', type: 'file', x: 220, y: 180, w: 660, name: 'app/routes/orders.py', who: 'example app', lines: ['@router.delete("/api/orders/{order_id}")'] },
        { id: 'models', type: 'file', x: 220, y: 320, w: 660, name: 'app/models.py', who: 'example app', lines: ['class Order(Base):', '    __tablename__ = "orders"'] },
        { id: 'mag', type: 'magnifier', x: 760, y: 0 },
        { id: 'call', type: 'chip', x: 940, y: 70, w: 450, who: 'http pack', text: 'call  DELETE /api/orders/42' },
        { id: 'ep', type: 'chip', x: 940, y: 210, w: 450, who: 'fastapi pack', text: 'DELETE /api/orders/{order_id}' },
        { id: 'tb', type: 'chip', x: 940, y: 350, w: 450, who: 'sqlalchemy pack', text: 'table  orders' },
        { id: 'policy', type: 'file', x: 220, y: 500, w: 660, name: '.gateforge/policies.yml', who: "owner's rules · shortened",
          lines: ['- id: user-facing-persistence', '  when:', '    exposure: user-facing', '  require:', '    - persistence:delete'] },
        { id: 'list', type: 'checklist', x: 940, y: 450, w: 460, title: 'must-prove list', max: 1 },
        { id: 'test', type: 'file', x: 220, y: 40, w: 700, name: 'tests/e2e/orders.spec.ts', who: 'by the agent',
          lines: ["test('deletes an order', { annotation: {", "  type: 'gateforge',", "  description: 'tenant.orders:persistence:delete',", '} }, async ({ page }) => { … });'] },
      ],
    },
    run: {
      ports: {
        in: [{ art: 'must-prove\nlist', from: 'Read the code', y: 150 }, { art: 'app\nrunning', from: 'Start the app', y: 665 }],
        out: { art: 'sealed\nreceipt', to: 'Grade', y: 400 },
      },
      lanes: [
        { id: 'runner', label: 'TEST RUNNER', y: 15, h: 245 },
        { id: 'referee', label: 'REFEREE (the witness)', y: 275, h: 250 },
        { id: 'app', label: 'APP + DATABASE', y: 540, h: 245 },
      ],
      actors: [
        { id: 'exp', type: 'checklist', x: 230, y: 322, w: 310, title: 'expected tests', max: 1 },
        { id: 'browser', type: 'browser', x: 230, y: 54, w: 520, url: '/orders', rows: [['41', 'cup'], ['42', 'pen'], ['43', 'ink']] },
        { id: 'sess', type: 'chip', x: 800, y: 64, text: 'session 7' },
        { id: 'verdict', type: 'chip', x: 1010, y: 150, text: 'runner says: passed ✓' },
        { id: 'key', type: 'key', x: 230, y: 330, label: "referee's key" },
        { id: 'proxy', type: 'proxy', x: 565, y: 300 },
        { id: 'ref', type: 'referee', x: 810, y: 292, label: 'referee' },
        { id: 'clip', type: 'clipboard', x: 975, y: 285, w: 430, rows: 4 },
        { id: 'receipt', type: 'receipt', x: 1110, y: 288 },
        { id: 'server', type: 'server', x: 590, y: 556, label: 'app server' },
        { id: 'db', type: 'db', x: 1050, y: 540, label: 'database', rows: [['41', 'cup'], ['42', 'pen'], ['43', 'ink']] },
      ],
    },
    grade: {
      ports: { in: [{ art: 'sealed\nreceipt', from: 'Test run' }], out: { art: 'verdicts', to: 'The gate' } },
      actors: [
        { id: 'receipt', type: 'receipt', x: 240, y: 70 },
        { id: 'list', type: 'checklist', x: 600, y: 90, w: 600, title: 'must-prove list', items: ['tenant.orders:persistence:delete'] },
        { id: 'map', type: 'file', x: 240, y: 420, w: 600, name: '.gateforge/test-map.yml', who: 'mapping = intent', lines: ['claims:', '  - tenant.orders:persistence:delete'] },
        { id: 'list2', type: 'checklist', x: 880, y: 430, w: 520, title: 'same item, nothing witnessed', items: ['tenant.orders:persistence:delete'] },
      ],
    },
    gate: {
      ports: { in: [{ art: 'verdicts', from: 'Grade' }], out: { art: 'commit\nlands', to: 'main' } },
      actors: [
        { id: 'snap', type: 'file', x: 230, y: 80, w: 340, name: 'Saved at Freeze', lines: ['Git tree ID: 9c2e…'] },
        { id: 'eq', type: 'label', x: 610, y: 96, text: '=', size: 80 },
        { id: 'now', type: 'folder', x: 740, y: 50, label: 'staged now\n(your repo)', fp: '' },
        { id: 'restage', type: 'chip', x: 240, y: 320, color: '#dc2626', text: 'Restage the intended bytes and run the pre-commit gate again.' },
        { id: 'gate', type: 'gate', x: 960, y: 380 },
        { id: 'term', type: 'terminal', x: 240, y: 560, w: 640, rows: 3 },
      ],
    },
  },

  steps: [
    /* ---------- forest ---------- */
    { at: 'forest', title: 'One commit, eight black boxes',
      text: 'Before an AI agent\'s commit lands, it passes through eight boxes, and box 6 runs three things at once.',
      actions: [{ boxesIn: true }] },
    { at: 'forest', title: 'The whole trip at a glance',
      text: 'Watch one commit travel through every box; then we open each box in turn.',
      actions: [{ journey: {} }],
      note: 'Our example the whole way: the agent adds "delete an order".' },

    /* ---------- 1 agent ---------- */
    { at: 'agent', title: 'The agent writes code',
      text: 'The agent adds a "delete an order" endpoint to the app.',
      actions: [{ show: 'robot' }, { show: 'code' }, { call: ['code', 'type'] }, { call: ['code', 'hi', 0] }],
      note: 'Remember DELETE /api/orders/42: we follow it to the end.' },
    { at: 'agent', title: 'It tries to commit',
      text: 'The agent runs git commit, and Git\'s pre-commit hook catches the commit before anything is saved.',
      actions: [{ show: 'term' }, { call: ['term', 'type', '$ git commit -m "add delete order"'] }, { show: 'hook' },
        { move: 'commit', from: 'term.r', to: 'hook.grab', keep: true }, { call: ['hook', 'grab'] },
        { show: 'help' }, { call: ['help', 'hi', 0] }],
      note: 'The commit is paused, not made.' },
    { at: 'agent', title: 'Hand-off to box 2',
      text: 'The hook hands the staged files to Gateforge, which is the next box.',
      actions: [{ out: true }, { move: 'staged files', from: 'hook.r', to: 'OUT' }] },

    /* ---------- 2 freeze ---------- */
    { at: 'freeze', title: 'Freeze: record the staged version',
      text: 'Gateforge records a Git tree ID for the exact staged version; this snapshot is not another folder.',
      actions: [{ show: 'staged' }, { move: 'staged files', from: 'IN', to: 'staged.l' }, { show: 'cam' },
        { call: ['cam', 'flash', 'staged'] }, { show: 'snap' }, { move: 'tree ID', from: 'staged.r', to: 'snap.l' }, { call: ['snap', 'hi', 0] }] },
    { at: 'freeze', title: 'Write that version into a scratch folder',
      text: 'Git writes the frozen version into one temporary checkout, where the app and tests run independently of your edits.',
      actions: [{ show: 'scratch' }, { move: 'checkout', from: 'snap.r', to: 'scratch.l' }, { call: ['scratch', 'pulse'] }, { show: 'robot' },
        { parallel: [[{ move: 'more edits', from: 'robot.t', to: 'staged.b', color: '#f59e0b' }, { call: ['staged', 'edit'] }], [{ wait: 500 }, { call: ['scratch', 'pulse'] }]] },
        { out: true }, { move: 'snapshot', from: 'scratch.r', to: 'OUT' }],
      note: 'One recorded version, one runnable checkout. Box 8 compares the saved tree ID with what is staged then.' },

    /* ---------- 3 owner ---------- */
    { at: 'owner', title: "Owner's OK: what could go wrong",
      text: 'The snapshot carries the rules files, and runtime.yml even holds commands Gateforge will run.',
      actions: [{ show: 'rules' }, { move: 'snapshot', from: 'IN', to: 'rules.l' }, { call: ['rules', 'hi', 4] }],
      note: 'An agent could quietly bend any of these rules.' },
    { at: 'owner', title: 'The rules get one fingerprint',
      text: 'Gateforge computes a single fingerprint over all of these rules files.',
      actions: [{ show: 'fp' }, { move: '5 files', from: 'rules.b', to: 'fp.t' }, { call: ['fp', 'pop'] }] },
    { at: 'owner', title: "Compare with the owner's pin",
      text: 'The owner pinned the fingerprint they approved in a place outside the repo, where the agent cannot write.',
      actions: [{ show: 'owner' }, { show: 'pin' }, { move: 'a3f9…', from: 'pin.l', to: 'fp.r' }, { mark: ['fp', 'ok'] },
        { out: true }, { move: 'approved recipe', from: 'fp.r', to: 'OUT' }],
      note: 'Same fingerprint, so the recipe may run (the pin is an opt-in owner setting).' },
    { at: 'owner', title: 'If the agent bends a rule',
      text: 'One changed line in runtime.yml gives a different fingerprint, so nothing starts.',
      actions: [{ show: 'robot' }, { move: 'edit', from: 'robot.l', to: 'rules:4.r', color: '#dc2626' }, { call: ['rules', 'bad', 4] },
        { call: ['fp', 'set', 'fingerprint  c71e…', '#dc2626'] }, { mark: ['fp', 'bad'] }, { out: 'bad' }, { show: 'block' }],
      note: 'Nothing runs until the owner approves and repins.' },

    /* ---------- 4 start ---------- */
    { at: 'start', title: 'Start the app from the snapshot',
      text: 'Gateforge runs the approved recipe and starts a fresh app and database built from the snapshot.',
      actions: [{ show: 'recipe' }, { move: 'approved recipe', from: 'IN', to: 'recipe.l' }, { call: ['recipe', 'hi', 0] }, { call: ['recipe', 'hi', 1] },
        { show: 'bar' }, { call: ['bar', 'fill'] }, { call: ['recipe', 'hi', 2] }, { call: ['recipe', 'hi', 3] },
        { show: ['snap', 'server', 'db'] },
        { parallel: [[{ move: 'start', from: 'snap.r', to: 'server.l' }], [{ move: 'start', from: 'snap.r', to: 'db.l' }]] },
        { call: ['server', 'up'] }],
      note: 'Not your dev server: a new app from the exact snapshot.' },
    { at: 'start', title: 'Is it alive?',
      text: 'A health check pings the app, and the run only begins once the light is green.',
      actions: [{ call: ['recipe', 'hi', 4] }, { call: ['recipe', 'hi', 5] }, { move: 'ping', from: 'recipe:5.r', to: 'server.l' },
        { move: 'ok', from: 'server.l', to: 'recipe:5.r', color: '#16a34a' }, { mark: ['server', 'ok'] }, { call: ['db', 'hiRow', '42'] },
        { out: true }, { move: 'app running', from: 'server.r', to: 'OUT' }],
      note: 'Row 42 (pen) is in the database. Keep an eye on it.' },

    /* ---------- 5 read ---------- */
    { at: 'read', title: 'Read the code',
      text: 'Three readers go through the snapshot one after another: frontend calls, routes, and database models.',
      actions: [{ show: ['front', 'routes', 'models'] }, { show: 'mag' },
        { call: ['mag', 'moveTo', 'front'] }, { show: 'call' }, { move: 'call', from: 'front.r', to: 'call.l' },
        { call: ['mag', 'moveTo', 'routes'] }, { show: 'ep' }, { move: 'endpoint', from: 'routes.r', to: 'ep.l' },
        { call: ['mag', 'moveTo', 'models'] }, { show: 'tb' }, { move: 'table', from: 'models.r', to: 'tb.l' }, { hide: 'mag' }] },
    { at: 'read', title: 'Connect the dots',
      text: 'The button\'s call is matched to the endpoint, and the endpoint to the table it changes.',
      actions: [{ connect: ['call.b', 'ep.t'], label: 'reaches' }, { connect: ['ep.b', 'tb.t'], label: 'changes' }],
      note: 'Gateforge now knows which button reaches which table.' },
    { at: 'read', title: 'Rule + table = something to prove',
      text: 'The owner\'s rule says user-facing tables must prove their changes, so "delete" lands on the must-prove list.',
      actions: [{ hide: ['front', 'routes', 'models'] }, { call: ['tb', 'set', 'table  orders · user-facing'] }, { show: 'policy' },
        { call: ['policy', 'hi', 2] }, { call: ['policy', 'hi', 4] }, { show: 'list' },
        { move: 'persistence:delete', from: 'policy:4.r', to: 'list:0.l' }, { call: ['list', 'add', 'tenant.orders:persistence:delete'] }, { call: ['list', 'hi', 0] }],
      note: 'Remember this name: a test will have to prove it.' },
    { at: 'read', title: 'Pick the tests',
      text: 'The test that names this exact item gets picked, and only tests for what changed will run.',
      actions: [{ unconnect: true }, { hide: ['call', 'ep', 'tb', 'policy'] }, { show: 'test' }, { call: ['test', 'hi', 2] },
        { connect: ['test:2.r', 'list:0.l'], color: '#ca8a04' }, { call: ['list', 'tag', 0, 'test: deletes an order', '#2563eb'] },
        { out: true }, { move: 'must-prove list', from: 'list.r', to: 'OUT' }] },

    /* ---------- 6 run ---------- */
    { at: 'run', title: 'Before anything runs',
      text: 'The referee first writes down which tests must run, so no test can quietly disappear.',
      actions: [{ lane: 'referee' }, { show: 'exp' }, { move: 'must-prove list', from: 'IN0', to: 'exp.l' }, { call: ['exp', 'add', 'deletes an order'] }] },
    { at: 'run', title: 'Three lanes at once',
      text: 'The test runner, the referee and the app now all work at the same time.',
      actions: [{ hide: 'exp' }, { parallel: [
        [{ lane: 'runner' }, { show: 'browser' }],
        [{ lane: 'referee' }, { show: ['proxy', 'ref', 'clip'] }],
        [{ lane: 'app' }, { move: 'app running', from: 'IN1', to: 'server.l' }, { show: ['server', 'db'] }, { call: ['server', 'up'] }],
      ] }] },
    { at: 'run', title: 'Each test gets a tag',
      text: 'The referee gives the test its own session tag, but its signing key never leaves the referee.',
      actions: [{ show: 'key' }, { show: 'sess' }, { move: 'session 7', from: 'ref.t', to: 'sess.b' },
        { move: 'key', from: 'key.k', to: 'browser.c', color: '#dc2626', blocked: true }],
      note: 'The test can be tagged, but it can never sign anything.' },
    { at: 'run', title: 'The click goes through the referee',
      text: 'The test clicks Delete, and the request passes the referee\'s checkpoint, gets stamped, and reaches the app.',
      actions: [{ call: ['browser', 'click', '42'] }, { parallel: [
        [{ move: 'DELETE /api/orders/42', from: 'browser:1.b', via: ['proxy.c'], to: 'server.t', stamp: { at: 1, text: 'session 7' } }],
        [{ wait: 1000 }, { call: ['clip', 'record', 's7  DELETE /api/orders/42'] }],
      ] }] },
    { at: 'run', title: 'The app deletes the row',
      text: 'The app removes row 42 from its database, and the answer 204 travels back the same way.',
      actions: [{ move: 'delete 42', from: 'server.r', to: 'db:1.l' }, { call: ['db', 'removeRow', '42'] },
        { move: '204', from: 'server.t', via: ['proxy.c'], to: 'browser:1.b', color: '#16a34a' }, { call: ['browser', 'removeRow', '42'] }] },
    { at: 'run', title: 'The referee checks for itself',
      text: 'The referee calls the app\'s reviewed adapter, which asks the backend for order 42 and gets "not found".',
      actions: [{ move: 'adapter.read(42)', from: 'ref.b', to: 'server.t' }, { move: 'not found', from: 'server.t', to: 'ref.b', color: '#16a34a' },
        { call: ['clip', 'record', 'tenant.orders:persistence:delete ✓', '#16a34a'] }],
      note: 'The referee checked; it did not take the test\'s word.' },
    { at: 'run', title: 'Now the same test, but mocked',
      text: 'A mocked test answers 204 inside the browser, so the request never reaches the referee or the app.',
      actions: [{ parallel: [[{ call: ['browser', 'restore'] }], [{ call: ['db', 'restore'] }]] }, { call: ['browser', 'mock'] },
        { call: ['browser', 'click', '42'] }, { move: 'DELETE /api/orders/42', from: 'browser:1.b', to: 'browser.mock', color: '#f59e0b' },
        { move: '204', from: 'browser.mock', to: 'browser:1.b', color: '#f59e0b' }, { call: ['browser', 'removeRow', '42'] },
        { call: ['db', 'hiRow', '42', '#dc2626'] }, { call: ['clip', 'record', 'mocked test: nothing seen', '#dc2626'] }],
      note: 'The page looks deleted, but row 42 is still there and the referee saw nothing.' },
    { at: 'run', title: 'The runner\'s own word',
      text: 'The test runner reports "passed" on its own, and that report never counts as proof.',
      actions: [{ call: ['browser', 'unmock'] }, { call: ['db', 'unhi'] }, { call: ['db', 'drop', '42'] },
        { show: 'verdict' }, { wait: 500 }, { call: ['verdict', 'strike'] }],
      note: 'A runner\'s own "passed" is never authority.' },
    { at: 'run', title: 'Seal the receipt',
      text: 'The referee turns its notes into receipt.json and signs it with the key the tests never had.',
      actions: [{ hide: 'clip' }, { show: 'receipt' }, { move: 'key', from: 'key.k', to: 'receipt.l' }, { call: ['receipt', 'seal'] },
        { out: true }, { move: 'sealed receipt', from: 'receipt.r', to: 'OUT' }],
      note: 'Signed with HMAC-SHA256, so a changed receipt no longer verifies.' },

    /* ---------- 7 grade ---------- */
    { at: 'grade', title: 'Grade: match proof to promises',
      text: 'Each witnessed record in the receipt is matched to an item on the must-prove list.',
      actions: [{ show: 'receipt' }, { move: 'sealed receipt', from: 'IN', to: 'receipt.l' }, { call: ['receipt', 'seal'] }, { show: 'list' },
        { move: 'witnessed record', from: 'receipt.r', to: 'list:0.l' }, { call: ['list', 'tick', 0] }, { call: ['list', 'tag', 0, 'satisfied', '#16a34a'] }] },
    { at: 'grade', title: 'A test that was only named',
      text: 'If a test only claims the item and the referee never saw proof, the item fails.',
      actions: [{ show: 'map' }, { call: ['map', 'hi', 1] }, { show: 'list2' }, { move: 'claim only', from: 'map:1.r', to: 'list2:0.l', color: '#6b7280' },
        { call: ['list2', 'cross', 0] }, { call: ['list2', 'tag', 0, 'EVIDENCE_NOT_COLLECTED', '#dc2626'] },
        { out: true }, { move: 'verdicts', from: 'list.r', to: 'OUT' }],
      note: 'Saying a test covers it is intent, never proof.' },

    /* ---------- 8 gate ---------- */
    { at: 'gate', title: 'Last check: same bytes?',
      text: 'Before saying yes, Gateforge compares the current staged Git tree ID with the one recorded in box 2.',
      actions: [{ mini: 'freeze' }, { show: 'snap' }, { call: ['snap', 'hi', 0] }, { show: 'now' }, { call: ['now', 'setFp', 'tree 9c2e…'] },
        { show: 'eq' }, { mark: ['now', 'ok'] }] },
    { at: 'gate', title: 'If the files changed meanwhile',
      text: 'If anything was restaged during the run, the fingerprints differ and the gate refuses.',
      actions: [{ call: ['now', 'setFp', 'tree 51ab…', '#dc2626'] }, { call: ['eq', 'set', '≠', '#dc2626'] }, { mark: ['now', 'bad'] }, { show: 'restage' }] },
    { at: 'gate', title: 'All proven: the gate opens',
      text: 'Every item is satisfied and the bytes match, so the barrier lifts and the commit lands.',
      actions: [{ hide: 'restage' }, { call: ['now', 'setFp', 'tree 9c2e…', '#111'] }, { call: ['eq', 'set', '=', '#111'] }, { mark: ['now', 'ok'] },
        { show: 'gate' }, { move: 'verdicts ✓', from: 'IN', to: 'gate.l', color: '#16a34a' }, { call: ['gate', 'open'] },
        { out: true }, { move: 'commit', from: 'gate.l', to: 'OUT', color: '#16a34a' }] },
    { at: 'gate', title: 'One missing proof: the gate stays shut',
      text: 'If even one item is missing, the barrier stays down and Gateforge names the one next thing to fix.',
      actions: [{ call: ['gate', 'close'] }, { out: 'bad' }, { move: 'commit', from: 'IN', to: 'gate.c', color: '#dc2626', blocked: true },
        { show: 'term' }, { call: ['term', 'type', '$ gateforge next'] }, { call: ['term', 'print', 'next: tenant.orders:persistence:delete'] },
        { call: ['term', 'print', 'cause: EVIDENCE_NOT_COLLECTED', '#dc2626'] }] },

    /* ---------- forest again ---------- */
    { at: 'forest', title: 'Back to the big picture',
      text: 'Every box did its part, so the commit made it all the way through.',
      actions: [{ journey: { tick: true } }] },
    { at: 'recap', title: 'The whole journey',
      text: 'One line per box.',
      actions: [
        { line: ['1  The agent commits; Git\'s hook pauses it.', ['agent']] },
        { line: ['2  Gateforge freezes the exact staged bytes into a snapshot.', ['freeze']] },
        { line: ['3  The owner\'s pin decides whether the rules and recipe may run.', ['owner']] },
        { line: ['4  A fresh app and database start from the snapshot.', ['start']] },
        { line: ['5  Reading the code turns "delete an order" into a must-prove item.', ['read']] },
        { line: ['6  Test, app and referee run together; the referee watches and checks.', ['run']] },
        { line: ['7–8  Proof meets promise, same bytes are confirmed, and the gate opens.', ['grade', 'gate']] },
      ] },
  ],
};
